export const OPEN_OBJECTIVES_REQUEST = 'OPEN_OBJECTIVES_REQUEST';
export const OPEN_OBJECTIVES_SUCCESS = 'OPEN_OBJECTIVES_SUCCESS';
export const OPEN_OBJECTIVES_FAILURE = 'OPEN_OBJECTIVES_FAILURE';
export const CLOSE_OBJECTIVES_REQUEST = 'CLOSE_OBJECTIVES_REQUEST';
export const CLOSE_OBJECTIVES_SUCCESS = 'CLOSE_OBJECTIVES_SUCCESS';
export const CLOSE_OBJECTIVES_FAILURE = 'CLOSE_OBJECTIVES_FAILURE';

export const GET_COMPANY_REQUEST = 'GET_COMPANY_REQUEST';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';
export const GET_COMPANY_FAILURE = 'GET_COMPANY_FAILURE';

export const GET_OBJECTIVES_REQUEST = 'GET_OBJECTIVES_REQUEST';
export const GET_DETAIL_OBJECTIVES_REQUEST = 'GET_DETAIL_OBJECTIVES_REQUEST';
export const GET_DETAIL_TOOBS_REQUEST = 'GET_DETAIL_TOOBS_REQUEST';
export const GET_INFO_OUTPUT_REQUEST = 'GET_INFO_OUTPUT_REQUEST';

export const GET_TOOB_BY_OBJECTIVES_REQUEST = 'GET_TOOB_BY_OBJECTIVES_REQUEST';
export const GET_TOOB_BY_OBJECTIVES_SUCCESS = 'GET_TOOB_BY_OBJECTIVES_SUCCESS';
export const GET_TOOB_BY_OBJECTIVES_FAILURE = 'GET_TOOB_BY_OBJECTIVES_FAILURE';

export const GET_MAP_REQUEST = 'GET_MAP_REQUEST';
export const GET_MAP_SUCCESS = 'GET_MAP_SUCCESS';
export const GET_MAP_FAILURE = 'GET_MAP_FAILURE';

export const POST_CREATE_TOOB_REQUEST = 'POST_CREATE_TOOB_REQUEST';
export const POST_CREATE_TOOB_SUCCESS = 'POST_CREATE_TOOB_SUCCESS';
export const POST_CREATE_TOOB_FAILURE = 'POST_CREATE_TOOB_FAILURE';

export const START_OBJECTIVE_REQUEST = 'START_OBJECTIVE_REQUEST';
export const START_OBJECTIVE_SUCCESS = 'START_OBJECTIVE_SUCCESS';
export const START_OBJECTIVE_FAILURE = 'START_OBJECTIVE_FAILURE';
