export const OPEN_CHAT_BOX_REQUEST = "OPEN_CHAT_BOX_REQUEST";
export const OPEN_CHAT_BOX_SUCCESS = "OPEN_CHAT_BOX_SUCCESS";
export const OPEN_CHAT_BOX_FAILURE = "OPEN_CHAT_BOX_FAILURE";
export const CLOSE_CHAT_BOX_REQUEST = "CLOSE_CHAT_BOX_REQUEST";
export const CLOSE_CHAT_BOX_SUCCESS = "CLOSE_CHAT_BOX_SUCCESS";
export const CLOSE_CHAT_BOX_FAILURE = "CLOSE_CHAT_BOX_FAILURE";
