export const OPEN_CHAT_BOX_REQUEST = 'OPEN_CHAT_BOX_REQUEST';
export const OPEN_CHAT_BOX_SUCCESS = 'OPEN_CHAT_BOX_SUCCESS';
export const OPEN_CHAT_BOX_FAILURE = 'OPEN_CHAT_BOX_FAILURE';

export const CLOSE_CHAT_BOX_REQUEST = 'CLOSE_CHAT_BOX_REQUEST';
export const CLOSE_CHAT_BOX_SUCCESS = 'CLOSE_CHAT_BOX_SUCCESS';
export const CLOSE_CHAT_BOX_FAILURE = 'CLOSE_CHAT_BOX_FAILURE';

export const GET_LIST_OBJ_REQUEST = 'GET_LIST_OBJ_REQUEST';
export const GET_LIST_OBJ_SUCCESS = 'GET_LIST_OBJ_SUCCESS';
export const GET_LIST_OBJ_FAILURE = 'GET_LIST_OBJ_FAILURE';
