export const GET_LIST_HUMAN_RESOURCES_REQUEST = 'GET_LIST_HUMAN_RESOURCES_REQUEST';
export const GET_LIST_HUMAN_RESOURCES_SUCCESS = 'GET_LIST_HUMAN_RESOURCES_SUCCESS';
export const GET_LIST_HUMAN_RESOURCES_FAILURE = 'GET_LIST_HUMAN_RESOURCES_FAILURE';

export const GET_LIST_USER_ACTIVE_REQUEST = 'GET_LIST_USER_ACTIVE_REQUEST';
export const GET_LIST_USER_ACTIVE_SUCCESS = 'GET_LIST_USER_ACTIVE_SUCCESS';
export const GET_LIST_USER_ACTIVE_FAILURE = 'GET_LIST_USER_ACTIVE_FAILURE';
